# Classification metrics

>  The decision on how to evaluai if an algorithm works balances the real-world use of the algorithm, the mathematical properties of the evaluation function, and the interpretability of the measure.

#### accuracy

fraction of correctly classified samples, to measure model performance.
from the confusion matrix: it's the sum of the diagonal divided by the total sum of the matrix.

> It is a simple measure that tells us what percentage of rows we got right.

####  Precision (positive predictive value or PPV)

the number of true positives divided by the total number of true positives and false positives.

#### Recall ( sensitivity, hit rate, or true positive rate)

the number of true positives divided by the total number of true positives and false negatives. 

#### F1-score 

two times the product of the precision and recall divided by the sum of the precision and recall, or the harmonic mean of precision and recall.

* For all metrics in scikit-learn, the first argument is always the true label and the prediction is always the second argument.

In [1]:
#imports for loading data
from sklearn import datasets
import numpy as np
#imports for training model
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier
#for evaluation
from sklearn.metrics import classification_report 
from sklearn.metrics import confusion_matrix 

In [2]:
#load dataset
iris = datasets.load_iris()
#prepare data
X = iris.data
y = iris.target

In [3]:
# Create training and test set
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=5555)

# Instantiate a k-NN classifier: knn
knn = KNeighborsClassifier(n_neighbors=6)

# Fit the classifier to the training data
knn.fit(X_train,y_train)

# Predict the labels of the test data: y_pred
y_pred = knn.predict(X_test)

In [4]:
# Generate the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[12  0  0]
 [ 0 16  1]
 [ 0  1 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.94      0.94      0.94        17
           2       0.94      0.94      0.94        16

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



#### Log loss 
generally called a "loss function", it is a measure of error. We want our error to be as small as possible, which is the opposite of a metric like accuracy, where we want to maximize the value.